/**
 * Email Service - Sends reports via email
 */
const nodemailer = require('nodemailer');
const fs = require('fs');
require('dotenv').config();

// Email configuration
const EMAIL_HOST = process.env.EMAIL_HOST || 'smtp.gmail.com';
const EMAIL_PORT = parseInt(process.env.EMAIL_PORT || '587');
const EMAIL_USER = process.env.EMAIL_USER;
const EMAIL_PASS = process.env.EMAIL_PASSWORD;
const EMAIL_FROM = process.env.EMAIL_FROM || EMAIL_USER;

/**
 * Create email transporter
 * @returns {Object} Nodemailer transporter
 */
function createTransporter() {
  if (!EMAIL_USER || !EMAIL_PASS) {
    console.warn('⚠ Email credentials not configured. Email sending will be disabled.');
    return null;
  }

  return nodemailer.createTransport({
    host: EMAIL_HOST,
    port: EMAIL_PORT,
    secure: EMAIL_PORT === 465, // true for 465, false for other ports
    auth: {
      user: EMAIL_USER,
      pass: EMAIL_PASS,
    },
  });
}

/**
 * Send report via email
 * @param {string} to - Recipient email address
 * @param {string} subject - Email subject
 * @param {string} body - Email body (HTML or plain text)
 * @param {string} pdfPath - Path to PDF file
 * @param {string} pdfFilename - PDF filename for attachment
 * @returns {Promise<Object>} Email send result
 */
async function sendReportEmail(to, subject, body, pdfPath, pdfFilename) {
  const transporter = createTransporter();
  
  if (!transporter) {
    throw new Error('Email service not configured. Please set EMAIL_USER and EMAIL_PASSWORD environment variables.');
  }

  if (!fs.existsSync(pdfPath)) {
    throw new Error(`PDF file not found: ${pdfPath}`);
  }

  try {
    const info = await transporter.sendMail({
      from: `"Hadir.AI Reports" <${EMAIL_FROM}>`,
      to: to,
      subject: subject,
      html: body,
      attachments: [
        {
          filename: pdfFilename,
          path: pdfPath,
          contentType: 'application/pdf',
        },
      ],
    });

    console.log('✓ Report email sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('✗ Error sending report email:', error);
    throw error;
  }
}

/**
 * Generate email body for monthly report
 * @param {Object} reportData - Report data
 * @returns {string} HTML email body
 */
function generateMonthlyReportEmailBody(reportData) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #4CAF50; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .summary { background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Monthly Attendance Report</h1>
        <p>${reportData.period.label}</p>
      </div>
      <div class="content">
        <h2>Report Summary</h2>
        <div class="summary">
          <p><strong>Total Employees:</strong> ${reportData.overall.totalEmployees}</p>
          <p><strong>Attendance Rate:</strong> ${reportData.overall.attendanceRate}</p>
          <p><strong>Pending Leave Requests:</strong> ${reportData.overall.pendingLeaves}</p>
          <p><strong>Open Tickets:</strong> ${reportData.overall.openTickets}</p>
        </div>
        <p>Please find the detailed report attached as a PDF.</p>
        <p>This is an automated report generated by Hadir.AI Attendance Management System.</p>
      </div>
      <div class="footer">
        <p>Hadir.AI - Attendance Management System</p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate email body for manual report
 * @param {Object} reportData - Report data
 * @returns {string} HTML email body
 */
function generateManualReportEmailBody(reportData) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .header { background-color: #2196F3; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .summary { background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Attendance Report</h1>
        <p>${reportData.period.label}</p>
      </div>
      <div class="content">
        <h2>Report Summary</h2>
        <div class="summary">
          <p><strong>Total Employees:</strong> ${reportData.overall.totalEmployees}</p>
          <p><strong>Attendance Rate:</strong> ${reportData.overall.attendanceRate}</p>
          <p><strong>Pending Leave Requests:</strong> ${reportData.overall.pendingLeaves}</p>
          <p><strong>Open Tickets:</strong> ${reportData.overall.openTickets}</p>
        </div>
        <p>Please find the detailed report attached as a PDF.</p>
        <p>This report was generated on request from the Hadir.AI Admin Dashboard.</p>
      </div>
      <div class="footer">
        <p>Hadir.AI - Attendance Management System</p>
        <p>This is an automated email. Please do not reply.</p>
      </div>
    </body>
    </html>
  `;
}

module.exports = {
  sendReportEmail,
  generateMonthlyReportEmailBody,
  generateManualReportEmailBody,
};

